language: php
sudo: required

services:
 - mysql

addons:
  hosts:
    - nexteuropa

git:
  depth: 1

php:
  - 5.6

env:
  - TEST=behat.0.yml
  - TEST=behat.1.yml
  - TEST=behat.2.yml
  - TEST=behat.3.yml
  - TEST=behat.4.yml

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.5
    - php: 7.0

mysql:
  database: nexteuropa
  username: root
  encoding: utf8

before_install:
  - phpenv config-rm xdebug.ini
  - phpenv rehash

install:
  # Install and setup Apache + FastCGI
  - sudo apt-get update > /dev/null
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  - ./resources/travis/setup-apache.sh
  # Run composer
  - composer self-update
  - composer install
  # Setup Phing
  - cp resources/travis/build.properties.local .
  # Build platform
  - ./bin/phing build-platform-dev
  - ./bin/phing install-platform
  - ./bin/phing setup-php-codesniffer
  - ./bin/phing setup-behat

before_script:
  - sudo service apache2 restart
  # Run PhamtomJS
  - phantomjs --version
  - phantomjs --webdriver=4444 > /dev/null &

script:
  - cd build/tests
  - cat ${TEST}
  - ./behat -c ${TEST}

after_failure:
  - cat error.log
  - cat access.log

notifications:
  email: true
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
