language: php
sudo: required

services:
 - mysql

addons:
  hosts:
    - nexteuropa
#  apt:
#    packages:
#      - mysql-server-5.6
#      - mysql-client-core-5.6
#      - mysql-client-5.6
#      - apache2
#      - libapache2-mod-php5

git:
  depth: 1

php:
  - 5.6

#env:
#  - TEST=behat.0.yml
#  - TEST=behat.1.yml
#  - TEST=behat.2.yml
#  - TEST=behat.3.yml
#  - TEST=behat.4.yml

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.5
    - php: 7.0

mysql:
  database: nexteuropa
  username: root
  encoding: utf8

before_install:
#  - phpenv config-rm xdebug.ini
#  - phpenv rehash
#  - phantomjs --version

install:
#  # Run composer
#  - composer self-update
#  - composer install
#  # Setup Phing
#  - cp resources/build.properties.travis build.properties.local
#  # Build platform
#  - ./bin/phing build-platform-dev
#  - ./bin/phing install-platform
#  - ./bin/phing setup-php-codesniffer
#  - ./bin/phing setup-behat
  - mkdir build
  - touch build/index.php
  - echo "<?php echo 'Hello';" >> build/index.php
  - touch build/README.txt
  - echo "Hello" >> build/README.txt
#  - sudo chmod a+x /home
#  - sudo chmod a+x /home/travis
#  - sudo chmod a+x /home/travis/build
#  - sudo chmod a+x /home/travis/build/ademarco
#  - sudo chmod a+x /home/travis/build/ademarco/platform-dev
#  - sudo chmod a+x -R /home/travis/build/ademarco/platform-dev/build

before_script:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - cat /etc/apache2/sites-available/*
  - sudo cp -f resources/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?PATH?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - cat /etc/apache2/sites-available/default
  - sudo service apache2 restart
#  - sudo a2enmod rewrite actions alias php5
#  # Configure apache virtual hosts
#  - cat /etc/apache2/sites-available/000-default.conf
#  - sudo cp -f resources/travis-ci-apache /etc/apache2/sites-available/000-default.conf
#  - sudo sed -i -e "s,PATH,$(pwd),g" /etc/apache2/sites-available/000-default.conf
#  - cat /etc/apache2/sites-available/000-default.conf
#  # Run Apache2
#  - sudo service apache2 restart
  # Run PhamtomJS
  - phantomjs --webdriver=4444 > /dev/null &

script:
  - curl http://nexteuropa
  - curl http://nexteuropa/README.txt
#  - cd build/tests
#  - ./behat -c ${TEST}

after_failure:
  - cat error.log
  - cat access.log

notifications:
  email: true
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
