language: php
sudo: required
dist: trusty

services:
 - mysql

addons:
  hosts:
    - nexteuropa
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
      - apache2
      - libapache2-mod-fastcgi

git:
  depth: 1

php:
  - 5.6

#env:
#  - TEST=behat.0.yml
#  - TEST=behat.1.yml
#  - TEST=behat.2.yml
#  - TEST=behat.3.yml
#  - TEST=behat.4.yml

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.5
    - php: 7.0

mysql:
  database: nexteuropa
  username: root
  encoding: utf8

before_install:
#  - phpenv config-rm xdebug.ini
#  - phpenv rehash
#  - phantomjs --version

install:
  # Run composer
#  - composer self-update
#  - composer install
#  # Setup Phing
#  - cp resources/build.properties.travis build.properties.local
  # Build platform
  - mkdir build
  - touch build/index.php
  - echo "echo 'Hello';" >> build/index.php
  - touch build/README.txt
  - echo "echo 'Hello';" >> build/README.txt
#  - ./bin/phing build-platform-dev
#  - ./bin/phing install-platform
#  - ./bin/phing setup-php-codesniffer
#  - ./bin/phing setup-behat

before_script:
  - curl http://nexteuropa
  # Enable PHP-FPM
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # Configure apache virtual hosts
  - sudo cp -f resources/travis-ci-apache /etc/apache2/sites-available/000-default.conf
  - sudo sed -i -e "s,PATH,$(pwd),g" /etc/apache2/sites-available/000-default.conf
  - cat /etc/apache2/sites-available/000-default.conf
  # Run Apache2
  - sudo service apache2 restart
  # Run PhamtomJS
  - phantomjs --webdriver=4444 > /dev/null &

script:
  - curl http://nexteuropa
  - curl http://nexteuropa/README.txt
#  - cd build/tests
#  - ./behat -c ${TEST}

notifications:
  email: true
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
