language: php
sudo: required
dist: trusty

services:
 - mysql

cache:
  directories:
    - "travis_phantomjs"

addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
      - apache2
      - libapache2-mod-php5

git:
  depth: 1

php:
  - '5.6'

env:
  - TEST=behat.0.yml
#  - TEST=behat.1.yml
#  - TEST=behat.2.yml
#  - TEST=behat.3.yml
#  - TEST=behat.4.yml

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.5
    - php: 7.0

mysql:
  database: nexteuropa
  username: root
  encoding: utf8

before_install:
  - phpenv config-rm xdebug.ini
  - phpenv rehash
  - export PHANTOMJS_VERSION=2.1.1
  - export PATH=$PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH;
  - export no_proxy="localhost,127.0.0.*"
  - export DISPLAY=:99.0
  - if [ $(phantomjs --version) != '2.1.1' ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs && wget https://assets.membergetmember.co/software/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 && tar -xvf $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi
  - phantomjs --version

install:
  # Run composer
#  - composer self-update
#  - composer install
  # Setup Phing
  - cp resources/build.properties.travis build.properties.local
  # Build platform
  - mkdir build
  - touch build/README.txt
#  - ./bin/phing build-platform-dev
#  - ./bin/phing install-platform
#  - ./bin/phing setup-php-codesniffer
#  - ./bin/phing setup-behat

before_script:
  # enable php-fpm
  - sudo a2enmod rewrite actions alias
  # Configure apache virtual hosts
  - sudo echo 127.0.0.1 platform.local >> /etc/hosts
  - sudo cp -f resources/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  # Run Apache
  - sudo service apache2 restart
  # Create DB
  - mysql -u root -e 'create database nexteuropa;'
  # Run PhamtomJS
  - phantomjs --webdriver=4444 > /dev/null &

script:
  - ls -al /home/travis/build/ademarco/platform-dev/build
  - sudo cat /etc/apache2/sites-available/default
  - curl http://platform.local/README.txt
  - curl http://localhost/README.txt
#  - cd build/tests
#  - ./behat -c ${TEST}

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
